### ISSUE TITLE
infotv/frontend/src directory is missing from git

### ISSUE THREAD

**Issue by japsu** [kcsry/infotv#2]
```
(venv-desusaitti)myrmidon:frontend japsu$ npm run build

> infotv@0.0.0 build /Users/japsu/Hobby/infotv/infotv/frontend
> webpack --verbose --progress

  0% compileEntryModuleNotFoundError: Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/main.js in /Users/japsu/Hobby/infotv/infotv/frontend
    at Tapable.<anonymous> (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/lib/Compilation.js:351:28)
    at Tapable.onDoneResolving (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/lib/NormalModuleFactory.js:28:20)
    at Tapable.<anonymous> (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/lib/NormalModuleFactory.js:83:20)
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/async/lib/async.js:251:17
    at done (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/async/lib/async.js:126:15)
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/async/lib/async.js:248:21
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/async/lib/async.js:572:34
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at evalmachine.<anonymous>:265:20
    at OpenReq.Req.done (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:141:5)
    at OpenReq.done (/Users/japsu/Hobby/infotv/infotv/frontend/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:61:22)
    at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
resolve file
  /Users/japsu/Hobby/infotv/infotv/frontend/src/main.js doesn't exist
  /Users/japsu/Hobby/infotv/infotv/frontend/src/main.js.webpack.js doesn't exist
  /Users/japsu/Hobby/infotv/infotv/frontend/src/main.js.web.js doesn't exist
  /Users/japsu/Hobby/infotv/infotv/frontend/src/main.js.js doesn't exist
  /Users/japsu/Hobby/infotv/infotv/frontend/src/main.js.json doesn't exist
resolve directory
  /Users/japsu/Hobby/infotv/infotv/frontend/src/main.js doesn't exist (directory default file)
  /Users/japsu/Hobby/infotv/infotv/frontend/src/main.js/package.json doesn't exist (directory description file)
```

**Comment by akx** [comment]
I'm officially a dummy. :)

Thanks for the catch!
